BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Urgent] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [State] NVARCHAR(1000) NOT NULL CONSTRAINT [Urgent_State_df] DEFAULT 'use',
    CONSTRAINT [Urgent_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
