BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[Job] ADD CONSTRAINT [Job_fromNodeId_fkey] FOREIGN KEY ([fromNodeId]) REFERENCES [dbo].[CallNodes]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[Job] ADD CONSTRAINT [Job_toNodeId_fkey] FOREIGN KEY ([toNodeId]) REFERENCES [dbo].[CallNodes]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
