BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[UserSections] ADD CONSTRAINT [UserSections_subSectionId_fkey] FOREIGN KEY ([subSectionId]) REFERENCES [dbo].[SubSections]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
