BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[JobRecord] ALTER COLUMN [fromNodeName] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[JobRecord] ALTER COLUMN [toNodeName] NVARCHAR(1000) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
