BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Sections] ADD [createdAt] DATETIME2 NOT NULL CONSTRAINT [Sections_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[updateAt] DATETIME2 NOT NULL CONSTRAINT [Sections_updateAt_df] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
